### PR TITLE
Add version info to the packages name

### PR DESCRIPTION
**Pull request by mcosta74**
This PR add version information in the packages' name

`nsc-linux-amd64.zip` -->  `nsc-2.6.1-linux-amd64.zip` 

Closes: #471

### CODE REVIEW

**Comment by aricart** [comment]
There's much more that needs doing for this to work, the self-update is looking for the versions in a specific way, so the change of the tag may create an issue here or there.

**Comment by aricart** [comment]
@wallyqs can you take a look if we can simply just change the tag and not break the self-update (up or down.

**Comment by mcosta74** [comment]
not 100% sure but the package `go-github-selfupdate` should be ok to download the right asset also if we change the archive name.

**Comment by wallyqs** [comment]
We just started supporting tagged versions for Go modules, so we can look into supporting this for next release.

**Pull request closed without merging**
