### PR TITLE
Remove vendored deps

### PR DESCRIPTION
**Pull request by bruth**
Includes an upgrade to Go 1.19

### CODE REVIEW

**Comment by bruth** [comment]
See all the errors.. fixing

**Review by wallyqs — APPROVED** [review]
LGTM

**Comment by wallyqs** [comment]
Let's make a release once this one is merged? @aricart @bruth

**Comment by bruth** [comment]
Thanks @wallyqs. Yes I agree. Is it as simple as pushing a new tag?

**Comment by wallyqs** [comment]
I think so, we can tag and push v2.7.3 release for now so that it is available to build the new Docker images:
https://github.com/nats-io/nsc/compare/2.7.2...main
There is a process for signing the releases as well for the artifacts /cc @philpennock

**Comment by bruth** [comment]
Ok, pushed the tag to kick off the build, but did not create the formal release yet.

**Pull request merged**
