### PR TITLE
fix: Generating of description for entities in combination of json and write to file.

### PR DESCRIPTION
**Pull request by Drakorgaur**
see issue https://github.com/nats-io/nsc/issues/594

### CODE REVIEW

**Comment by aricart** [comment]
@Drakorgaur great find thanks

**Review by aricart — CHANGES_REQUESTED** [review]
I'll add a test

**Review by aricart — APPROVED** [review]

**Comment by Drakorgaur** [comment]
> The fix is super simple, can you add a test for it, if not I can add it for you

yes, no problem.
Can it wait for tommorow then?

**Comment by aricart** [comment]
I'll do them! - it will be much less painful on you.

**Comment by Drakorgaur** [comment]
> I'll do them! - it will be much less painful on you.

thanks! 😄

**Pull request merged**
