### PR TITLE
use correct import path for survey

### PR DESCRIPTION
**Pull request by ripienaar**
The import path for survey should be `gopkg.in/AlecAivazis/survey.v1` but
`github.com/AlecAivazis/survey` was used in this project, anyone who uses
`go mod` to load anything from this project would end up needing both 
paths in their dependencies as the module internally use the gopkg one.

### CODE REVIEW

**Comment by ripienaar** [comment]
I am not sure why my mod vendor deleted the `olang.org/x/sys/unix` and `golang.org/x/text/unicode` stuff though, perhaps because I am on go 1.13 and some of these are now in core?

**Comment by aricart** [comment]
I was about to upgrade to v2 today.

**Comment by ripienaar** [comment]
awesome, I noticed v2 after this PR and was going to do it for you :) So if you'll fix the path when you do that we can kill this PR

**Comment by aricart** [comment]
Sounds good. There's a few changes I have to make.

**Comment by ripienaar** [comment]
@aricart any update on this v2 business?

**Comment by aricart** [comment]
not yet - started work on it, but will be refactoring all the
cli widgets along with that change.

**Comment by aricart** [comment]
This is fixed by #242.

**Pull request closed without merging**
